cta:
  bucket: null
  version: null
  domain: null
name: audio~x
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
typography_spectrum: 0.7240143
color:
  saturation: 0.8685149541124701
  brandStrength: 0.9749104
  rhythmicContrast: 0.3193129552528262
  brandColors:
    - '#161615'
    - '#424341'
    - '#FFFBE0'
    - '#AB8053'
    - '#284A90'
  lightness: 0.9767499445006251
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
